export default [
  {
    _id: 1,
    points: 100,
    name: 'name',
    category: 'Categoria 1',
  },
  {
    _id: 2,
    points: 200,
    name: 'name2',
    category: 'Categoria 1',
  },
  {
    _id: 3,
    points: 300,
    name: 'name3',
    category: 'Categoria 1',
  },
  {
    _id: 4,
    points: 400,
    name: 'name4',
    category: 'Categoria 1',
  },
  {
    _id: 5,
    points: 500,
    name: 'name5',
    category: 'Categoria 1',
  },
  {
    _id: 6,
    points: 100,
    name: 'name6',
    category: 'Categoria 2',
  },
  {
    _id: 7,
    points: 200,
    name: 'name7',
    category: 'Categoria 2',
  },
  {
    _id: 8,
    points: 300,
    name: 'name8',
    category: 'Categoria 2',
  },
  {
    _id: 9,
    points: 400,
    name: 'name9',
    category: 'Categoria 2',
  },
  {
    _id: 10,
    points: 500,
    name: 'name10',
    category: 'Categoria 2',
  },
  {
    _id: 11,
    points: 100,
    name: 'name11',
    category: 'Categoria 3',
  },
  {
    _id: 12,
    points: 200,
    name: 'name12',
    category: 'Categoria 3',
  },
  {
    _id: 13,
    points: 300,
    name: 'name13',
    category: 'Categoria 3',
  },
  {
    _id: 14,
    points: 400,
    name: 'name14',
    category: 'Categoria 3',
  },
  {
    _id: 15,
    points: 500,
    name: 'name15',
    category: 'Categoria 3',
  },
  {
    _id: 16,
    points: 100,
    name: 'name16',
    category: 'Categoria 4',
  },
  {
    _id: 17,
    points: 200,
    name: 'name17',
    category: 'Categoria 4',
  },
  {
    _id: 18,
    points: 300,
    name: 'name18',
    category: 'Categoria 4',
  },
  {
    _id: 19,
    points: 400,
    name: 'name19',
    category: 'Categoria 4',
  },
  {
    _id: 20,
    points: 500,
    name: 'name20',
    category: 'Categoria 4',
  },
];
